services:
  - docker

before_script:
  - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  - echo $TRAVIS_TAG

deploy:
  provider: script
  script: bash docker_push
  on:
    tags: true

branches:
  only:
    - test
