apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-server
  labels:
    app: api-gateway
data:
  maps.conf: |
    include /etc/nginx/customization.d/maps-http-accept-extension.conf;
    include /etc/nginx/customization.d/maps-original-request-uri.conf;
    include /etc/nginx/customization.d/maps-proxyName.conf;
    include /etc/nginx/customization.d/maps-proxyUrl.conf;
    include /etc/nginx/customization.d/maps-proxyVersion.conf;
    include /etc/nginx/customization.d/maps-proxyPrefix.conf;
    include /etc/nginx/customization.d/maps-type.conf;
  resolver.conf: |
    resolver 127.0.0.1 ipv6=off;
    set_real_ip_from 127.0.0.1;         # trust localhost
    set_real_ip_from unix:;             # trust local unix socket
    set_real_ip_from 10.0.0.0/8;        # trust class A private networks
    set_real_ip_from 172.16.0.0/12;     # trust class B private networks
    set_real_ip_from 192.168.0.0/16;    # trust class C private networks
    real_ip_header X-Forwarded-For;
  upstream.conf: |
    upstream unauthorized { server unix:/tmp/unauthorized.sock; }
    upstream not_found { server unix:/tmp/not_found.sock; }
