name: api-gateway-release

on:
  push:
    tags:
      - '*'

jobs:
  api-gateway-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push 
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: riccardoatzori/api-gateway:latest