name: api-gateway-release

on:
  push:
    tags:
      - '*'

jobs:
  api-gateway-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1


      - name: Build and Push 
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: riccardoatzori/api-gateway:latest